[tool.black]
line-length = 99
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
    \.github
    \.vscode
  | \.venv
  | docs
  | node_modules
  | tests/integrations/templates
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true